# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

pod 'RollbarCrash', :modular_headers => true
pod 'RollbarReport', :modular_headers => true
pod 'RollbarCommon', :modular_headers => true
pod 'RollbarNotifier', :modular_headers => true

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'hymnbook2' do
  config = use_native_modules!
  use_frameworks! :linkage => :static

  pod 'RollbarReactNative', path: '../node_modules/rollbar-react-native'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'hymnbook2Tests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Fix for Xcode 26.4 build error
    installer.pods_project.targets.each do |target|
      if target.name == 'fmt'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end
      end


      if target.name == 'RollbarReactNative'
        target.build_configurations.each do |config|
          # Fix for private header error in RollbarReachability
          pods_dir = File.join(installer.sandbox.root, 'RollbarNotifier')
          Dir.glob(File.join(pods_dir, '**', 'RollbarReachability.m')).each do |file|
            if File.exist?(file)
              content = File.read(file)
              if content.include?('#import <netinet6/in6.h>')
                # Grant write permission if the file is read-only
                FileUtils.chmod("u+w", file)
                new_content = content.gsub('#import <netinet6/in6.h>', '')
                File.write(file, new_content)
                puts "[Post-Install] Removed private header from #{file}"
              end
            end
          end
        end
      end
    end
  end
end
