require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'hymnbook2' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])







  target 'hymnbook2Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
    flipper_post_install(installer)
  end
end

target 'hymnbook2-tvOS' do
  # Pods for hymnbook2-tvOS

  target 'hymnbook2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
