import { ColorValue } from "react-native";

export interface ThemeColors {
  tint: ColorValue,
  tint1: ColorValue,
  tintLight: ColorValue,
  height0: ColorValue,
  height1: ColorValue,
  height2: ColorValue,
  height3: ColorValue,
  height4: ColorValue,
  height5: ColorValue,
  height6: ColorValue,
  height7: ColorValue,
  height8: ColorValue,
  text0: ColorValue,
  text1: ColorValue,
  text2: ColorValue,
  text3: ColorValue,
  text4: ColorValue,
  text5: ColorValue,
  text6: ColorValue,
  text7: ColorValue,
  textHeader: ColorValue,
  url0: ColorValue,
  border0: ColorValue,
  border1: ColorValue,
  verseTitle: ColorValue,
}

export const lightColors: ThemeColors = {
  tint: "dodgerblue",
  tint1: "dodgerblue",
  tintLight: "#63adff",
  height0: "#f1f1f1",
  height1: "#fcfcfc",
  height2: "#fff",
  height3: "#ddd",
  height4: "#f7f7f7",
  height5: "#eee",
  height6: "#707070",
  height7: "#fcfcfc",
  height8: "#fff",
  text0: "#000",
  text1: "#555",
  text2: "#8d8d8e",
  text3: "#aaa",
  text4: "#ddd",
  text5: "#ccc",
  text6: "#373737",
  text7: "#8f979a",
  textHeader: "#1c1c1c",
  url0: "#57a4fd",
  border0: "#ddd",
  border1: "#eee",
  verseTitle: "#333"
};

export const darkColors: ThemeColors = {
  tint: "dodgerblue",
  tint1: "#1576d5",
  tintLight: "#2776cc",
  height0: "#202020",
  height1: "#303030",
  height2: "#3a3a3a",
  height3: "#404040",
  height4: "#3a3a3a",
  height5: "#555",
  height6: "#3a3a3a",
  height7: "#3a3a3a",
  height8: "#4a4a4a",
  text0: "#eee",
  text1: "#ccc",
  text2: "#ccc",
  text3: "#bbb",
  text4: "#ddd",
  text5: "#ccc",
  text6: "#ccc",
  text7: "#eee",
  textHeader: "#eee",
  url0: "#57a4fd",
  border0: "#202020",
  border1: "#202020",
  verseTitle: "#e0e0e0"
};

